# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=64)),
                ('representative', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=64, null=True)),
                ('telephone', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
