# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 13:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=16)),
                ('department', models.FloatField()),
                ('section', models.FloatField()),
                ('date_joined', models.DateField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'ordering': ['department', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='nombre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='c\xf3digo')),
                ('serial', models.CharField(max_length=34, verbose_name='n\xfamero de serie')),
                ('specifications', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('state', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bueno'), (2, 'En reparaci\xf3n'), (3, 'Da\xf1ado')], null=True, verbose_name='estado')),
                ('invoice', models.CharField(blank=True, max_length=16, null=True)),
                ('date_purchase', models.DateField(blank=True, null=True)),
                ('date_warranty', models.DateField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True, verbose_name='observaciones')),
                ('in_set', models.BooleanField(default=False)),
                ('owner', models.CharField(blank=True, max_length=16, verbose_name='propietario')),
            ],
            options={
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nombre')),
                ('part_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='parte #')),
                ('specifications', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocktaking.Brand', verbose_name='marca')),
            ],
            options={
                'ordering': ['type', 'brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=7)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocktaking.Model')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='nombre')),
                ('icon', models.ImageField(upload_to='sets', verbose_name='icono')),
            ],
        ),
        migrations.CreateModel(
            name='SetDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipments', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='equipos')),
                ('owner', models.CharField(blank=True, max_length=16, null=True, verbose_name='propietario')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocktaking.Set')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='nombre')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='c\xf3digo')),
                ('usage', models.PositiveSmallIntegerField(default=1, verbose_name='uso')),
                ('image', models.ImageField(blank=True, null=True, upload_to='types', verbose_name='icono')),
            ],
            options={
                'ordering': ['usage', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TypeSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(max_length=32)),
                ('order', models.PositiveSmallIntegerField(verbose_name='orden')),
                ('label', models.CharField(max_length=128, verbose_name='nombre')),
                ('choices', models.CharField(blank=True, max_length=256, null=True, verbose_name='choices')),
                ('widget', models.CharField(max_length=64)),
                ('is_required', models.BooleanField(default=False, verbose_name='requerido?')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_specifications', to='stocktaking.Type')),
            ],
            options={
                'ordering': ['-when', 'order'],
            },
        ),
        migrations.AddField(
            model_name='set',
            name='types',
            field=models.ManyToManyField(to='stocktaking.Type', verbose_name='tipos'),
        ),
        migrations.AddField(
            model_name='model',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocktaking.Type', verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocktaking.Model', verbose_name='modelo'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.Provider'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocktaking.Equipment'),
        ),
    ]
