# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 21:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=16)),
                ('department', models.FloatField()),
                ('section', models.FloatField()),
                ('date_joined', models.DateField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'ordering': ['department', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('serial', models.CharField(blank=True, max_length=34, null=True, unique=True)),
                ('part', models.CharField(blank=True, max_length=32, null=True)),
                ('specifications', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=16, null=True)),
                ('invoice', models.CharField(blank=True, max_length=16, null=True)),
                ('date_purchase', models.DateField(blank=True, null=True)),
                ('date_warranty', models.DateField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('part_number', models.CharField(blank=True, max_length=32, null=True)),
                ('specifications', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocktaking.Brand')),
                ('replacements', models.ManyToManyField(blank=True, related_name='_model_replacements_+', to='stocktaking.Model')),
            ],
            options={
                'ordering': ['type', 'brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=7)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocktaking.Model')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('usage', models.PositiveSmallIntegerField(default=1)),
                ('specifications', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('when', models.CharField(max_length=32)),
                ('options', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_specifications', to='stocktaking.Type')),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
        migrations.AddField(
            model_name='model',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocktaking.Type'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocktaking.Model'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.Provider'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocktaking.Equipment'),
        ),
    ]
