# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocktaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='accessory_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocktaking.Equipment'),
        ),
    ]
