# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('charter', models.CharField(db_column='ctrcedula', max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='ctrnombre', max_length=120, null=True)),
                ('email', models.CharField(blank=True, db_column='ctremail', max_length=60, null=True)),
                ('state', models.CharField(blank=True, db_column='ctrestado', max_length=20, null=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'contribuyentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.FloatField(db_column='coddepar', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nomdepar', max_length=60)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('code', models.CharField(db_column='biprvcodigo', max_length=2, primary_key=True, serialize=False)),
                ('department', models.FloatField(blank=True, db_column='bicoddep', null=True)),
                ('section', models.FloatField(blank=True, db_column='bicodsec', null=True)),
            ],
            options={
                'ordering': ['contributor'],
                'db_table': 'bicondep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('code', models.FloatField(db_column='codseccion', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nomseccion', max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'secciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nombre')),
                ('address', models.CharField(max_length=128, verbose_name='direcci\xf3n')),
            ],
        ),
    ]
